# Generated by Django 4.2 on 2023-04-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dummy_app', '0002_source_article_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='django_dummy_app.source'),
        ),
        migrations.CreateModel(
            name='ArticleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=512)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='django_dummy_app.article')),
            ],
        ),
    ]
